import { JSXMapSerializer, PrismicProvider } from "@prismicio/react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrismicNextLink } from "@prismicio/next";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */
export const richTextComponents: JSXMapSerializer = {
  heading1: ({ children }) => (
    <h1 className="mb-8 font-title last:mb-0">{children}</h1>
  ),
  heading2: ({ children }) => (
    <h3 className="mb-2 font-title text-6xl font-bold  last:mb-0">
      {children}
    </h3>
  ),
  heading3: ({ children }) => (
    <h4 className="mb-2  text-xl last:mb-0">{children}</h4>
  ),
  heading4: ({ children }) => (
    <h5 className="mb-2  text-lg last:mb-0">{children}</h5>
  ),
  heading5: ({ children }) => (
    <h5 className="mb-2  text-base last:mb-0">{children}</h5>
  ),
  paragraph: ({ children }) => <p className="mb-7 last:mb-0">{children}</p>,
  oList: ({ children }) => (
    <ol className="mb-7 pl-4 last:mb-0 md:pl-6">{children}</ol>
  ),
  oListItem: ({ children }) => (
    <li className="mb-1 list-decimal pl-1 last:mb-0 md:pl-2">{children}</li>
  ),
  list: ({ children }) => (
    <ul className="mb-7 pl-4 last:mb-0 md:pl-6">{children}</ul>
  ),
  listItem: ({ children }) => (
    <li className="mb-1 list-disc pl-1 last:mb-0 md:pl-2">{children}</li>
  ),
  preformatted: ({ children }) => (
    <pre className="mb-7 rounded p-4 text-sm last:mb-0 md:p-8 md:text-lg">
      <code>{children}</code>
    </pre>
  ),
  strong: ({ children }) => (
    <strong className="font-semibold">{children}</strong>
  ),
  hyperlink: ({ children, node }) => (
    <PrismicNextLink
      field={node.data}
      className="underline decoration-1 underline-offset-2"
    >
      {children}
    </PrismicNextLink>
  ),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
